/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.duitang.service.l2;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface L2Service {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"L2Service\",\"namespace\":\"com.duitang.service.l2\",\"types\":[],\"messages\":{\"cat_setstring\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"},{\"name\":\"ttl\",\"type\":\"int\"}],\"response\":\"boolean\"},\"cat_addstring\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"},{\"name\":\"ttl\",\"type\":\"int\"}],\"response\":\"boolean\"},\"cat_incr\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"delta\",\"type\":\"long\"}],\"response\":\"long\"},\"cat_getstring\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"}],\"response\":\"string\"},\"cat_delstring\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"}],\"response\":\"boolean\"},\"cat_mgetstring\":{\"request\":[{\"name\":\"keys\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}],\"response\":{\"type\":\"map\",\"values\":\"string\"}},\"session_getsession\":{\"request\":[{\"name\":\"sessionid\",\"type\":\"string\"}],\"response\":{\"type\":\"map\",\"values\":[\"string\",\"null\",\"long\",\"int\",\"float\",\"double\"]}},\"session_get\":{\"request\":[{\"name\":\"sessionid\",\"type\":\"string\"}],\"response\":\"string\"},\"session_set\":{\"request\":[{\"name\":\"sessionid\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"}],\"response\":\"boolean\"},\"session_expire\":{\"request\":[{\"name\":\"sessionid\",\"type\":\"string\"},{\"name\":\"expiryage\",\"type\":\"int\"}],\"response\":\"long\"},\"session_delete\":{\"request\":[{\"name\":\"sessionid\",\"type\":\"string\"}],\"response\":\"long\"}}}");
  boolean cat_setstring(java.lang.CharSequence key, java.lang.CharSequence value, int ttl) throws org.apache.avro.AvroRemoteException;
  boolean cat_addstring(java.lang.CharSequence key, java.lang.CharSequence value, int ttl) throws org.apache.avro.AvroRemoteException;
  long cat_incr(java.lang.CharSequence key, long delta) throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence cat_getstring(java.lang.CharSequence key) throws org.apache.avro.AvroRemoteException;
  boolean cat_delstring(java.lang.CharSequence key) throws org.apache.avro.AvroRemoteException;
  java.util.Map<java.lang.CharSequence,java.lang.CharSequence> cat_mgetstring(java.util.List<java.lang.CharSequence> keys) throws org.apache.avro.AvroRemoteException;
  java.util.Map<java.lang.CharSequence,java.lang.Object> session_getsession(java.lang.CharSequence sessionid) throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence session_get(java.lang.CharSequence sessionid) throws org.apache.avro.AvroRemoteException;
  boolean session_set(java.lang.CharSequence sessionid, java.lang.CharSequence value) throws org.apache.avro.AvroRemoteException;
  long session_expire(java.lang.CharSequence sessionid, int expiryage) throws org.apache.avro.AvroRemoteException;
  long session_delete(java.lang.CharSequence sessionid) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends L2Service {
    public static final org.apache.avro.Protocol PROTOCOL = com.duitang.service.l2.L2Service.PROTOCOL;
    void cat_setstring(java.lang.CharSequence key, java.lang.CharSequence value, int ttl, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void cat_addstring(java.lang.CharSequence key, java.lang.CharSequence value, int ttl, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void cat_incr(java.lang.CharSequence key, long delta, org.apache.avro.ipc.Callback<java.lang.Long> callback) throws java.io.IOException;
    void cat_getstring(java.lang.CharSequence key, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void cat_delstring(java.lang.CharSequence key, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void cat_mgetstring(java.util.List<java.lang.CharSequence> keys, org.apache.avro.ipc.Callback<java.util.Map<java.lang.CharSequence,java.lang.CharSequence>> callback) throws java.io.IOException;
    void session_getsession(java.lang.CharSequence sessionid, org.apache.avro.ipc.Callback<java.util.Map<java.lang.CharSequence,java.lang.Object>> callback) throws java.io.IOException;
    void session_get(java.lang.CharSequence sessionid, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void session_set(java.lang.CharSequence sessionid, java.lang.CharSequence value, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void session_expire(java.lang.CharSequence sessionid, int expiryage, org.apache.avro.ipc.Callback<java.lang.Long> callback) throws java.io.IOException;
    void session_delete(java.lang.CharSequence sessionid, org.apache.avro.ipc.Callback<java.lang.Long> callback) throws java.io.IOException;
  }
}