/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.duitang.service.demo;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface DemoService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"DemoService\",\"namespace\":\"com.duitang.service.demo\",\"types\":[],\"messages\":{\"memory_getString\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"}],\"response\":\"string\"},\"memory_setString\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"},{\"name\":\"ttl\",\"type\":\"int\"}],\"response\":\"boolean\"},\"memory_getBytes\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"}],\"response\":\"bytes\"},\"memory_setBytes\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"bytes\"},{\"name\":\"ttl\",\"type\":\"int\"}],\"response\":\"boolean\"}}}");
  java.lang.CharSequence memory_getString(java.lang.CharSequence key) throws org.apache.avro.AvroRemoteException;
  boolean memory_setString(java.lang.CharSequence key, java.lang.CharSequence value, int ttl) throws org.apache.avro.AvroRemoteException;
  java.nio.ByteBuffer memory_getBytes(java.lang.CharSequence key) throws org.apache.avro.AvroRemoteException;
  boolean memory_setBytes(java.lang.CharSequence key, java.nio.ByteBuffer value, int ttl) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends DemoService {
    public static final org.apache.avro.Protocol PROTOCOL = com.duitang.service.demo.DemoService.PROTOCOL;
    void memory_getString(java.lang.CharSequence key, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void memory_setString(java.lang.CharSequence key, java.lang.CharSequence value, int ttl, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void memory_getBytes(java.lang.CharSequence key, org.apache.avro.ipc.Callback<java.nio.ByteBuffer> callback) throws java.io.IOException;
    void memory_setBytes(java.lang.CharSequence key, java.nio.ByteBuffer value, int ttl, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}