/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.duitang.service.karma.base;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Dummy {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Dummy\",\"namespace\":\"com.duitang.service.base\",\"types\":[],\"messages\":{\"dummy_dummy\":{\"request\":[],\"response\":\"null\"}}}");
  java.lang.Void dummy_dummy() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Dummy {
    public static final org.apache.avro.Protocol PROTOCOL = com.duitang.service.karma.base.Dummy.PROTOCOL;
    void dummy_dummy(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}